<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Motor;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MotorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all()->keyBy('name');

        $motors = [
            // Bebek/Gigi (5 models)
            [
                'name' => 'Honda Supra X 125 FI',
                'category_id' => $categories['Gigi']->id,
                'price' => 18500000,
                'model_year' => '2024',
                'engine_cc' => 125,
                'colors' => ['#C70039', '#000000', '#1E40AF'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '9.3 HP @ 7500 rpm',
                    'Torsi Maksimum' => '10.3 Nm @ 6000 rpm',
                    'Transmisi' => '4-Speed Manual',
                    'Kapasitas Tangki' => '4.2 liter',
                    'Panjang' => '2010 mm',
                    'Lebar' => '720 mm',
                    'Tinggi' => '1050 mm',
                    'Jarak Sumbu Roda' => '1280 mm',
                    'Berat Kosong' => '105 kg',
                    'Ban Depan' => '70/90-17',
                    'Ban Belakang' => '80/90-17',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Ganda',
                    'Rem Depan' => 'Cakram',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['CBS', 'Fuel Injection', 'Electric Starter', 'Digital Meter'],
                'description' => 'Motor bebek andalan dengan teknologi Fuel Injection untuk efisiensi bahan bakar dan performa optimal.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 4.2,
                'is_featured' => true,
                'slug' => 'honda-supra-x-125-fi',
            ],
            [
                'name' => 'Honda Revo X',
                'category_id' => $categories['Gigi']->id,
                'price' => 16800000,
                'model_year' => '2024',
                'engine_cc' => 110,
                'colors' => ['#C70039', '#000000', '#94A3B8'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 2-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'Karburator',
                    'Tenaga Maksimum' => '8.36 HP @ 7500 rpm',
                    'Torsi Maksimum' => '8.84 Nm @ 5500 rpm',
                    'Transmisi' => '4-Speed Manual',
                    'Kapasitas Tangki' => '3.7 liter',
                    'Panjang' => '1935 mm',
                    'Lebar' => '705 mm',
                    'Tinggi' => '1090 mm',
                    'Jarak Sumbu Roda' => '1245 mm',
                    'Berat Kosong' => '98 kg',
                    'Ban Depan' => '70/90-17',
                    'Ban Belakang' => '80/90-17',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Ganda',
                    'Rem Depan' => 'Tromol',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['CBS', 'Electric Starter', 'Economy Mode'],
                'description' => 'Motor bebek ekonomis dengan performa handal dan hemat bahan bakar untuk kebutuhan sehari-hari.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 3.7,
                'is_featured' => false,
                'slug' => 'honda-revo-x',
            ],
            [
                'name' => 'Honda Genio',
                'category_id' => $categories['Gigi']->id,
                'price' => 17500000,
                'model_year' => '2024',
                'engine_cc' => 110,
                'colors' => ['#0D9488', '#F59E0B', '#1E293B'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 2-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '8.8 HP @ 7500 rpm',
                    'Torsi Maksimum' => '9.3 Nm @ 5500 rpm',
                    'Transmisi' => '4-Speed Manual',
                    'Kapasitas Tangki' => '4.4 liter',
                    'Panjang' => '1925 mm',
                    'Lebar' => '710 mm',
                    'Tinggi' => '1090 mm',
                    'Jarak Sumbu Roda' => '1260 mm',
                    'Berat Kosong' => '101 kg',
                    'Ban Depan' => '70/90-17',
                    'Ban Belakang' => '80/90-17',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Ganda',
                    'Rem Depan' => 'Tromol',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['CBS', 'Fuel Injection', 'USB Charger', 'Digital Meter'],
                'description' => 'Motor bebek modern dengan desain stylish dan fitur modern untuk generasi muda.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 4.4,
                'is_featured' => true,
                'slug' => 'honda-genio',
            ],
            [
                'name' => 'Honda MegaPro',
                'category_id' => $categories['Gigi']->id,
                'price' => 22500000,
                'model_year' => '2024',
                'engine_cc' => 160,
                'colors' => ['#000000', '#D4D4D4', '#1E3A8A'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '15.5 HP @ 8000 rpm',
                    'Torsi Maksimum' => '13.4 Nm @ 6500 rpm',
                    'Transmisi' => '5-Speed Manual',
                    'Kapasitas Tangki' => '12.2 liter',
                    'Panjang' => '2060 mm',
                    'Lebar' => '765 mm',
                    'Tinggi' => '1080 mm',
                    'Jarak Sumbu Roda' => '1340 mm',
                    'Berat Kosong' => '135 kg',
                    'Ban Depan' => '90/90-17',
                    'Ban Belakang' => '120/80-17',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['CBS', 'Fuel Injection', 'Sporty Design', 'LED Lighting'],
                'description' => 'Motor sport touring dengan performa tinggi dan kenyamanan jarak jauh.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 12.2,
                'is_featured' => true,
                'slug' => 'honda-megapro',
            ],
            [
                'name' => 'Honda Verza',
                'category_id' => $categories['Gigi']->id,
                'price' => 21500000,
                'model_year' => '2024',
                'engine_cc' => 150,
                'colors' => ['#B91C1C', '#000000', '#F97316'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '12.4 HP @ 8000 rpm',
                    'Torsi Maksimum' => '12.7 Nm @ 6000 rpm',
                    'Transmisi' => '5-Speed Manual',
                    'Kapasitas Tangki' => '12 liter',
                    'Panjang' => '2040 mm',
                    'Lebar' => '780 mm',
                    'Tinggi' => '1080 mm',
                    'Jarak Sumbu Roda' => '1330 mm',
                    'Berat Kosong' => '128 kg',
                    'Ban Depan' => '80/100-17',
                    'Ban Belakang' => '100/90-17',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['CBS', 'Fuel Injection', 'Sporty Design', 'Digital Meter'],
                'description' => 'Motor naked sport dengan desain modern dan performa tangguh untuk berbagai medan.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 12.0,
                'is_featured' => false,
                'slug' => 'honda-verza',
            ],

            // Matic (8 models)
            [
                'name' => 'Honda Vario 125',
                'category_id' => $categories['Matic']->id,
                'price' => 22500000,
                'model_year' => '2024',
                'engine_cc' => 125,
                'colors' => ['#FFFFFF', '#000000', '#EF4444', '#6B7280'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '11.1 HP @ 8500 rpm',
                    'Torsi Maksimum' => '10.8 Nm @ 5000 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '5.5 liter',
                    'Panjang' => '1910 mm',
                    'Lebar' => '685 mm',
                    'Tinggi' => '1095 mm',
                    'Jarak Sumbu Roda' => '1275 mm',
                    'Berat Kosong' => '108 kg',
                    'Ban Depan' => '90/90-12',
                    'Ban Belakang' => '100/90-10',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['Smart Key', 'LED Lighting', 'Digital Meter', 'Idling Stop System'],
                'description' => 'Skutik premium dengan teknologi Smart Key dan performa optimal untuk perkotaan.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 5.5,
                'is_featured' => true,
                'slug' => 'honda-vario-125',
            ],
            [
                'name' => 'Honda Beat Street',
                'category_id' => $categories['Matic']->id,
                'price' => 19200000,
                'model_year' => '2024',
                'engine_cc' => 110,
                'colors' => ['#FFD700', '#DC2626', '#1E40AF', '#000000'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 2-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '9.0 HP @ 8000 rpm',
                    'Torsi Maksimum' => '9.0 Nm @ 5500 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '4.2 liter',
                    'Panjang' => '1870 mm',
                    'Lebar' => '670 mm',
                    'Tinggi' => '1080 mm',
                    'Jarak Sumbu Roda' => '1240 mm',
                    'Berat Kosong' => '99 kg',
                    'Ban Depan' => '80/90-14',
                    'Ban Belakang' => '90/90-14',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['LED Headlight', 'Digital Speedometer', 'Combi Brake System'],
                'description' => 'Skutik sporty dengan desain street fighter dan efisiensi bahan bakar terbaik di kelasnya.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 4.2,
                'is_featured' => false,
                'slug' => 'honda-beat-street',
            ],
            [
                'name' => 'Honda PCX 160',
                'category_id' => $categories['Matic']->id,
                'price' => 32500000,
                'model_year' => '2024',
                'engine_cc' => 160,
                'colors' => ['#000000', '#1E293B', '#EF4444', '#FFFFFF'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '16.0 HP @ 8500 rpm',
                    'Torsi Maksimum' => '15.0 Nm @ 6500 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '8.1 liter',
                    'Panjang' => '1940 mm',
                    'Lebar' => '745 mm',
                    'Tinggi' => '1110 mm',
                    'Jarak Sumbu Roda' => '1315 mm',
                    'Berat Kosong' => '132 kg',
                    'Ban Depan' => '100/80-14',
                    'Ban Belakang' => '120/70-14',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['Smart Key', 'ABS', 'Full LED', 'Idling Stop System', 'Digital Meter'],
                'description' => 'Skutik premium dengan teknologi canggih dan performa tinggi untuk pengendara modern.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 8.1,
                'is_featured' => true,
                'slug' => 'honda-pcx-160',
            ],
            [
                'name' => 'Honda ADV 160',
                'category_id' => $categories['Matic']->id,
                'price' => 35500000,
                'model_year' => '2024',
                'engine_cc' => 160,
                'colors' => ['#1E293B', '#F59E0B', '#065F46'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '16.0 HP @ 8500 rpm',
                    'Torsi Maksimum' => '15.0 Nm @ 6500 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '8.1 liter',
                    'Panjang' => '1960 mm',
                    'Lebar' => '760 mm',
                    'Tinggi' => '1190 mm',
                    'Jarak Sumbu Roda' => '1320 mm',
                    'Berat Kosong' => '134 kg',
                    'Ban Depan' => '110/80-14',
                    'Ban Belakang' => '130/70-13',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['Smart Key', 'ABS', 'Full LED', 'Idling Stop System', 'All-Terrain Tires'],
                'description' => 'Skutik adventure dengan desain tangguh dan kemampuan off-road ringan untuk penjelajahan kota maupun alam.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 8.1,
                'is_featured' => true,
                'slug' => 'honda-adv-160',
            ],
            [
                'name' => 'Honda Scoopy',
                'category_id' => $categories['Matic']->id,
                'price' => 21500000,
                'model_year' => '2024',
                'engine_cc' => 110,
                'colors' => ['#F472B6', '#3B82F6', '#F59E0B', '#000000'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 2-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '9.0 HP @ 8000 rpm',
                    'Torsi Maksimum' => '9.0 Nm @ 5500 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '4.2 liter',
                    'Panjang' => '1870 mm',
                    'Lebar' => '670 mm',
                    'Tinggi' => '1080 mm',
                    'Jarak Sumbu Roda' => '1240 mm',
                    'Berat Kosong' => '99 kg',
                    'Ban Depan' => '80/90-14',
                    'Ban Belakang' => '90/90-14',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['Smart Key', 'LED Headlight', 'Retro Design', 'Digital Meter'],
                'description' => 'Skutik retro dengan gaya klasik dan fitur modern untuk pengendara stylish.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 4.2,
                'is_featured' => false,
                'slug' => 'honda-scoopy',
            ],
            [
                'name' => 'Honda Click 125',
                'category_id' => $categories['Matic']->id,
                'price' => 20800000,
                'model_year' => '2024',
                'engine_cc' => 125,
                'colors' => ['#3B82F6', '#10B981', '#EF4444', '#1E293B'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '11.1 HP @ 8500 rpm',
                    'Torsi Maksimum' => '10.8 Nm @ 5000 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '5.5 liter',
                    'Panjang' => '1910 mm',
                    'Lebar' => '685 mm',
                    'Tinggi' => '1095 mm',
                    'Jarak Sumbu Roda' => '1275 mm',
                    'Berat Kosong' => '108 kg',
                    'Ban Depan' => '90/90-12',
                    'Ban Belakang' => '100/90-10',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['Smart Key', 'LED Lighting', 'Idling Stop System', 'USB Charger'],
                'description' => 'Skutik modern dengan fitur lengkap dan efisiensi bahan bakar terbaik untuk mobilitas perkotaan.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 5.5,
                'is_featured' => false,
                'slug' => 'honda-click-125',
            ],
            [
                'name' => 'Honda Forza 250',
                'category_id' => $categories['Matic']->id,
                'price' => 75500000,
                'model_year' => '2024',
                'engine_cc' => 250,
                'colors' => ['#000000', '#1E293B', '#FFFFFF'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '24.0 HP @ 8500 rpm',
                    'Torsi Maksimum' => '23.0 Nm @ 6250 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '11.0 liter',
                    'Panjang' => '2140 mm',
                    'Lebar' => '755 mm',
                    'Tinggi' => '1470 mm',
                    'Jarak Sumbu Roda' => '1510 mm',
                    'Berat Kosong' => '182 kg',
                    'Ban Depan' => '120/70-15',
                    'Ban Belakang' => '140/70-14',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['Smart Key', 'ABS', 'Full LED', 'Adjustable Windscreen', 'Digital Meter'],
                'description' => 'Maxi-scooter premium dengan performa tinggi dan kenyamanan maksimal untuk touring jarak jauh.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 11.0,
                'is_featured' => true,
                'slug' => 'honda-forza-250',
            ],
            [
                'name' => 'Honda Giorno',
                'category_id' => $categories['Matic']->id,
                'price' => 24500000,
                'model_year' => '2024',
                'engine_cc' => 110,
                'colors' => ['#F59E0B', '#3B82F6', '#10B981', '#FFFFFF'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 2-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '9.0 HP @ 8000 rpm',
                    'Torsi Maksimum' => '9.0 Nm @ 5500 rpm',
                    'Transmisi' => 'Otomatis V-Matic',
                    'Kapasitas Tangki' => '4.2 liter',
                    'Panjang' => '1870 mm',
                    'Lebar' => '670 mm',
                    'Tinggi' => '1080 mm',
                    'Jarak Sumbu Roda' => '1240 mm',
                    'Berat Kosong' => '99 kg',
                    'Ban Depan' => '80/90-14',
                    'Ban Belakang' => '90/90-14',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Tromol'
                ],
                'features' => ['Smart Key', 'LED Lighting', 'Retro Design', 'USB Charger'],
                'description' => 'Skutik retro dengan sentuhan modern dan fitur canggih untuk gaya hidup perkotaan.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'CVT',
                'fuel_capacity' => 4.2,
                'is_featured' => false,
                'slug' => 'honda-giorno',
            ],

            // Sport (4 models)
            [
                'name' => 'Honda CBR150R',
                'category_id' => $categories['Sport']->id,
                'price' => 35500000,
                'model_year' => '2024',
                'engine_cc' => 150,
                'colors' => ['#EF4444', '#000000', '#3B82F6'],
                'specifications' => [
                    'Tipe Mesin' => 'DOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '17.1 HP @ 9000 rpm',
                    'Torsi Maksimum' => '14.4 Nm @ 7000 rpm',
                    'Transmisi' => '6-Speed Manual',
                    'Kapasitas Tangki' => '12.1 liter',
                    'Panjang' => '1970 mm',
                    'Lebar' => '700 mm',
                    'Tinggi' => '1080 mm',
                    'Jarak Sumbu Roda' => '1320 mm',
                    'Berat Kosong' => '139 kg',
                    'Ban Depan' => '90/80-17',
                    'Ban Belakang' => '130/70-17',
                    'Suspensi Depan' => 'Teleskopik Upside Down',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['ABS', 'Full LED', 'Digital Meter', 'Slipper Clutch', 'Sporty Design'],
                'description' => 'Sport bike premium dengan teknologi MotoGP dan performa tinggi untuk pengendara sport.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 12.1,
                'is_featured' => true,
                'slug' => 'honda-cbr150r',
            ],
            [
                'name' => 'Honda CBR250RR',
                'category_id' => $categories['Sport']->id,
                'price' => 75500000,
                'model_year' => '2024',
                'engine_cc' => 250,
                'colors' => ['#000000', '#1E293B', '#EF4444'],
                'specifications' => [
                    'Tipe Mesin' => 'DOHC 4-stroke, 8-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '41.0 HP @ 13000 rpm',
                    'Torsi Maksimum' => '25.0 Nm @ 11000 rpm',
                    'Transmisi' => '6-Speed Manual',
                    'Kapasitas Tangki' => '14.5 liter',
                    'Panjang' => '2060 mm',
                    'Lebar' => '725 mm',
                    'Tinggi' => '1090 mm',
                    'Jarak Sumbu Roda' => '1380 mm',
                    'Berat Kosong' => '168 kg',
                    'Ban Depan' => '110/70-17',
                    'Ban Belakang' => '140/70-17',
                    'Suspensi Depan' => 'Teleskopik Upside Down',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['ABS', 'Quick Shifter', 'Full LED', 'Riding Modes', 'Digital Meter'],
                'description' => 'Sport bike kelas premium dengan performa maksimal dan teknologi canggih untuk pengendara profesional.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 14.5,
                'is_featured' => true,
                'slug' => 'honda-cbr250rr',
            ],
            [
                'name' => 'Honda CB150R StreetFire',
                'category_id' => $categories['Sport']->id,
                'price' => 28500000,
                'model_year' => '2024',
                'engine_cc' => 150,
                'colors' => ['#000000', '#1E293B', '#EF4444', '#FFFFFF'],
                'specifications' => [
                    'Tipe Mesin' => 'DOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '17.1 HP @ 9000 rpm',
                    'Torsi Maksimum' => '14.4 Nm @ 7000 rpm',
                    'Transmisi' => '6-Speed Manual',
                    'Kapasitas Tangki' => '12.0 liter',
                    'Panjang' => '2020 mm',
                    'Lebar' => '785 mm',
                    'Tinggi' => '1050 mm',
                    'Jarak Sumbu Roda' => '1320 mm',
                    'Berat Kosong' => '136 kg',
                    'Ban Depan' => '110/70-17',
                    'Ban Belakang' => '150/60-17',
                    'Suspensi Depan' => 'Teleskopik Upside Down',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['ABS', 'Full LED', 'Neo Sports Cafe Design', 'Digital Meter'],
                'description' => 'Naked sport dengan desain neo-retro dan performa tinggi untuk gaya perkotaan.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 12.0,
                'is_featured' => true,
                'slug' => 'honda-cb150r-streetfire',
            ],
            [
                'name' => 'Honda CRF150L',
                'category_id' => $categories['Sport']->id,
                'price' => 32500000,
                'model_year' => '2024',
                'engine_cc' => 150,
                'colors' => ['#EF4444', '#000000', '#10B981'],
                'specifications' => [
                    'Tipe Mesin' => 'SOHC 4-stroke, 4-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '13.1 HP @ 8500 rpm',
                    'Torsi Maksimum' => '12.4 Nm @ 6500 rpm',
                    'Transmisi' => '5-Speed Manual',
                    'Kapasitas Tangki' => '8.5 liter',
                    'Panjang' => '2080 mm',
                    'Lebar' => '815 mm',
                    'Tinggi' => '1190 mm',
                    'Jarak Sumbu Roda' => '1340 mm',
                    'Berat Kosong' => '128 kg',
                    'Ban Depan' => '80/100-21',
                    'Ban Belakang' => '100/100-18',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['Off-Road Capability', 'Long Travel Suspension', 'LED Headlight', 'Digital Meter'],
                'description' => 'Dual-sport bike dengan kemampuan on-road dan off-road untuk petualangan segala medan.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 8.5,
                'is_featured' => true,
                'slug' => 'honda-crf150l',
            ],

            // Trill/Naked (3 models)
            [
                'name' => 'Honda CB500F',
                'category_id' => $categories['Trill']->id,
                'price' => 95500000,
                'model_year' => '2024',
                'engine_cc' => 500,
                'colors' => ['#000000', '#1E293B', '#EF4444'],
                'specifications' => [
                    'Tipe Mesin' => 'DOHC 4-stroke, 8-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '47.0 HP @ 8500 rpm',
                    'Torsi Maksimum' => '43.0 Nm @ 7000 rpm',
                    'Transmisi' => '6-Speed Manual',
                    'Kapasitas Tangki' => '16.7 liter',
                    'Panjang' => '2080 mm',
                    'Lebar' => '790 mm',
                    'Tinggi' => '1060 mm',
                    'Jarak Sumbu Roda' => '1410 mm',
                    'Berat Kosong' => '189 kg',
                    'Ban Depan' => '120/70-17',
                    'Ban Belakang' => '160/60-17',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['ABS', 'Full LED', 'Digital Meter', 'Sporty Design'],
                'description' => 'Naked bike dengan performa tinggi dan kenyamanan untuk penggunaan sehari-hari.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 16.7,
                'is_featured' => true,
                'slug' => 'honda-cb500f',
            ],
            [
                'name' => 'Honda CB650R',
                'category_id' => $categories['Trill']->id,
                'price' => 155500000,
                'model_year' => '2024',
                'engine_cc' => 650,
                'colors' => ['#1E293B', '#000000', '#D4D4D4'],
                'specifications' => [
                    'Tipe Mesin' => 'DOHC 4-stroke, 16-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '95.0 HP @ 12000 rpm',
                    'Torsi Maksimum' => '64.0 Nm @ 8500 rpm',
                    'Transmisi' => '6-Speed Manual',
                    'Kapasitas Tangki' => '15.4 liter',
                    'Panjang' => '2120 mm',
                    'Lebar' => '780 mm',
                    'Tinggi' => '1070 mm',
                    'Jarak Sumbu Roda' => '1450 mm',
                    'Berat Kosong' => '202 kg',
                    'Ban Depan' => '120/70-17',
                    'Ban Belakang' => '180/55-17',
                    'Suspensi Depan' => 'Teleskopik Upside Down',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['ABS', 'Quick Shifter', 'Full LED', 'Riding Modes', 'TFT Display'],
                'description' => 'Naked bike premium dengan performa tinggi dan desain neo-retro yang ikonik.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 15.4,
                'is_featured' => true,
                'slug' => 'honda-cb650r',
            ],
            [
                'name' => 'Honda Rebel 500',
                'category_id' => $categories['Trill']->id,
                'price' => 98500000,
                'model_year' => '2024',
                'engine_cc' => 500,
                'colors' => ['#1E293B', '#000000', '#D4D4D4', '#B45309'],
                'specifications' => [
                    'Tipe Mesin' => 'DOHC 4-stroke, 8-valve',
                    'Sistem Pendingin' => 'Air',
                    'Sistem Bahan Bakar' => 'PGM-FI',
                    'Tenaga Maksimum' => '47.0 HP @ 8500 rpm',
                    'Torsi Maksimum' => '43.0 Nm @ 7000 rpm',
                    'Transmisi' => '6-Speed Manual',
                    'Kapasitas Tangki' => '11.2 liter',
                    'Panjang' => '2190 mm',
                    'Lebar' => '820 mm',
                    'Tinggi' => '1090 mm',
                    'Jarak Sumbu Roda' => '1490 mm',
                    'Berat Kosong' => '190 kg',
                    'Ban Depan' => '130/90-16',
                    'Ban Belakang' => '150/80-16',
                    'Suspensi Depan' => 'Teleskopik',
                    'Suspensi Belakang' => 'Monoshock',
                    'Rem Depan' => 'Cakram Hidrolik',
                    'Rem Belakang' => 'Cakram Hidrolik'
                ],
                'features' => ['ABS', 'LED Lighting', 'Cruiser Design', 'Digital Meter'],
                'description' => 'Cruiser dengan desain klasik dan performa modern untuk gaya berkendara santai.',
                'fuel_type' => 'Gasoline',
                'transmission' => 'Manual',
                'fuel_capacity' => 11.2,
                'is_featured' => true,
                'slug' => 'honda-rebel-500',
            ],
        ];

        foreach ($motors as $motor) {
            Motor::create($motor);
        }
    }
}
